Calendar is routed and is rendering on app.
fern-herm/pet-plant-sitting pull request #24
Opened 2022-06-15 18:25 UTC by velouriagreen

2022-06-15 18:28 UTC, royce-reed commented
what's the difference btw pages/calendar.tsx and pages/calenderMain.tsx?

2022-06-15 18:45 UTC, iAmGjert requested changes
I would say just fix the useState thing I mentioned and everything else looks fine.

2022-06-16 00:57 UTC, iAmGjert approved these changes

2022-06-16 16:23 UTC, royce-reed approved these changes

2022-06-16 16:35 UTC, Ibenyourbro approved these changes

2022-06-16 16:36 UTC, merged