In the Chat, Clients Can See Applicants and Applicants Can See Clients
fern-herm/pet-plant-sitting pull request #73
Opened 2022-06-30 17:04 UTC by raymondjjeong

2022-06-30 18:59 UTC, iAmGjert commented on client/src/Components/Chat/ApplicantList.tsx
> +    const jobs = await axios.get('/api/jobs/all');
I could be wrong, but I think this same information is already in state. You could probably avoid an axios call and just useAppSelector(state=>state.job.jobs);

2022-06-30 19:00 UTC, iAmGjert commented on client/src/Components/Chat/ClientList.tsx
> +    const jobs = await axios.get('/api/jobs/all');
Same as previous comment

2022-06-30 19:03 UTC, iAmGjert requested changes
I think I found a few things that could change here.

2022-07-04 14:49 UTC, royce-reed approved these changes

2022-07-04 14:54 UTC, iAmGjert approved these changes

2022-07-04 14:54 UTC, merged