Fixed bugs in landing page and updated calendar/scheduler to include both jobs and events
fern-herm/pet-plant-sitting pull request #81
Opened 2022-07-03 18:41 UTC by velouriagreen

2022-07-03 18:45 UTC, royce-reed requested changes
please resolve conflicts

2022-07-04 03:13 UTC, royce-reed approved these changes

2022-07-04 03:14 UTC, Ibenyourbro approved these changes

2022-07-04 14:57 UTC, iAmGjert approved these changes

2022-07-04 14:57 UTC, merged